<a href="https://colab.research.google.com/github/Mahdi-Miri/TensorFlow/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://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@github.com/Mahdi-Miri/TensorFlow.git

Cloning into 'TensorFlow'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.


In [4]:
import tensorflow as tf

In [5]:
a = tf.constant(3)

In [6]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [9]:
b = tf.constant([1,3,4])

In [10]:
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 4], dtype=int32)>

In [11]:
 c = tf.constant([[1,2,3],[3,4,5]])

In [12]:
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

In [15]:
d = tf.constant([[[1,2,3],[3,4,5]],[[1,2,3],[3,4,5]]])

In [16]:
d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]]], dtype=int32)>

In [18]:
a = tf.constant([1,2,])
b = tf.constant([3,4])

In [19]:
c = tf.add(a,b)

In [20]:
c

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [21]:
c.numpy()

array([4, 6], dtype=int32)

In [25]:
d = tf.subtract(b,a)

In [26]:
d.numpy()

array([2, 2], dtype=int32)

In [33]:
a_1 = tf.constant([[1,2],[3,4]])

In [34]:
b_1 = tf.constant([[1,2],[3,4]])

In [35]:
ew = tf.multiply(a_1,b_1)

In [36]:
ew

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [37]:
mm = tf.matmul(a_1,b_1)

In [38]:
mm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [39]:
d = tf.divide(a,b)

In [40]:
d

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.33333333, 0.5       ])>

In [41]:
a = tf.constant([1,2,3,])

In [42]:
b = tf.constant(4)

In [43]:
c = a *b

In [44]:
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  8, 12], dtype=int32)>

In [45]:
c = a + b

In [46]:
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 6, 7], dtype=int32)>

In [50]:
a = tf.constant([1,2,3,4,5,6])

In [51]:
a.shape

TensorShape([6])

In [52]:
b = tf.reshape(a,[2,3])

In [53]:
b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [54]:
b.shape

TensorShape([2, 3])

In [55]:
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [56]:
b = tf.expand_dims(a,-1)

In [57]:
b

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)>

In [66]:
a = tf.constant([[1,2],[3,4.0]])

In [67]:
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [68]:
 b =tf.square(a)

In [69]:
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  4.],
       [ 9., 16.]], dtype=float32)>

In [70]:
b = tf.sqrt(a)

In [71]:
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.4142135],
       [1.7320508, 2.       ]], dtype=float32)>

In [72]:
c = tf.reduce_min(a)

In [73]:
c

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [74]:
avg = tf.reduce_mean(a)

In [78]:
avg.numpy()

2.5

In [79]:
std = tf.math.reduce_std(a)

In [80]:
std.numpy()

1.118034