<a href="https://colab.research.google.com/github/Mahdi-Miri/TensorFlow/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://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@github.com/Mahdi-Miri/TensorFlow.git

Cloning into 'TensorFlow'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.


In [4]:
import tensorflow as tf

In [5]:
a = tf.constant(3)

In [6]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [9]:
b = tf.constant([1,3,4])

In [10]:
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 4], dtype=int32)>

In [11]:
 c = tf.constant([[1,2,3],[3,4,5]])

In [12]:
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

In [15]:
d = tf.constant([[[1,2,3],[3,4,5]],[[1,2,3],[3,4,5]]])

In [16]:
d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]]], dtype=int32)>

In [18]:
a = tf.constant([1,2,])
b = tf.constant([3,4])

In [19]:
c = tf.add(a,b)

In [20]:
c

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [21]:
c.numpy()

array([4, 6], dtype=int32)

In [25]:
d = tf.subtract(b,a)

In [26]:
d.numpy()

array([2, 2], dtype=int32)

In [33]:
a_1 = tf.constant([[1,2],[3,4]])

In [34]:
b_1 = tf.constant([[1,2],[3,4]])

In [35]:
ew = tf.multiply(a_1,b_1)

In [36]:
ew

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [37]:
mm = tf.matmul(a_1,b_1)

In [38]:
mm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [39]:
d = tf.divide(a,b)

In [40]:
d

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.33333333, 0.5       ])>